name: cogsci-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - ruptures
  - celluloid
  - imageio
  - pip:
    - factor_analyzer